version: 2
updates:
# Enable version updates for Python/pip
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "main"
  allow:
  - dependency-type: "all"
  versioning-strategy: "increase"
  labels:
  - "dependencies"
  - "python"
  # Auto-merge configuration
  auto-merge: true

# Enable version updates for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "main"
  labels:
  - "dependencies"
  - "github-actions"
  # Auto-merge configuration
  auto-merge: true
