version: 2
updates:
# Enable version updates for Python/pip
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  open-pull-requests-limit: 10
  labels:
  - "dependencies"
  - "python"
  # Auto-merge configuration
  auto-merge: true
  versioning-strategy: auto
  # Only auto-merge patch and minor updates
  ignore:
  - dependency-name: "*"
    update-types: [ "version-update:semver-major" ]

# Enable version updates for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  open-pull-requests-limit: 10
  labels:
  - "dependencies"
  - "github-actions"
  # Auto-merge configuration
  auto-merge: true
  versioning-strategy: auto
  # Only auto-merge patch and minor updates
  ignore:
  - dependency-name: "*"
    update-types: [ "version-update:semver-major" ]
