version: '3.8'

services:
  crs-bot:
    build: .
    volumes:
      - .:/app:ro  # Mount current directory read-only for development
      - data:/app/data  # Use simple volume mount since we initialize it properly
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}  # From .env file or environment
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    user: crsbot
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.github.com/zen')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  data:  # Use default volume driver 