version: '3.8'

services:
  crs-bot:
    build: .
    volumes:
      - .:/app:ro  # Mount current directory read-only for development
      - data:/app/data  # Persistent volume for data
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}  # From .env file or environment
      - PYTHONUNBUFFERED=1
      - TEST_ENV=${TEST_ENV}  # From .env file or environment
    restart: unless-stopped
    user: crsbot
    healthcheck:
      test: ["CMD", "python", "-c", "import os; import time; log_file = '/app/data/github_release_bot.log'; assert os.path.exists(log_file) and os.access(log_file, os.W_OK), 'Log file not accessible'; time.sleep(5); with open(log_file, 'r') as f: content = f.read(); assert 'Starting new release check' in content, 'Application not started'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  data:
    name: data 