name: Update Dependencies
on:
  repository_dispatch:
    types: [ dependency-update ]

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Update requirements.txt
      run: |
        echo "requests>=2.31.0" > requirements.txt.tmp
        tail -n +2 requirements.txt >> requirements.txt.tmp
        mv requirements.txt.tmp requirements.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PAT_TOKEN }}
        commit-message: "build(deps): update requests to latest version"
        title: "build(deps): update requests to latest version"
        body: "Update requests package to latest version"
        branch: "deps/update-requests"
        labels: |
          dependencies
          python 
