name: Manual Dependabot
on:
  workflow_dispatch:


jobs:
  dependabot:
    name: 'Dependabot'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0

    - name: Close existing PRs
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        echo "Looking for existing dependency PRs..."
        prs=$(gh pr list --json number,author,labels,title --jq '.[] | select((.author.login == "dependabot[bot]") or (.labels | map(.name) | contains(["dependencies"]))) | .number')
        if [ ! -z "$prs" ]; then
          echo "Found PRs to close: $prs"
          echo "$prs" | while read -r pr; do
            echo "Closing PR #$pr"
            gh pr close "$pr" --comment "Closing to recreate with latest changes"
            sleep 2
          done
        else
          echo "No existing dependency PRs found"
        fi

    - name: Create fresh dependency PR
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Configure git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        # Create a new branch for dependencies
        git checkout -b "deps/update-all"

        # Update dependencies in requirements.txt
        if [ -f "requirements.txt" ]; then
          echo "Updating requirements.txt..."
          # Create a temporary file with updated versions
          {
            echo "requests>=2.31.0"
            echo "pytest>=7.4.3"
            echo "pytest-cov>=4.1.0"
            echo "black>=23.11.0"
            echo "flake8>=6.1.0"
            echo "isort>=5.12.0"
            echo "mypy>=1.7.0"
          } > requirements.txt.new
          
          # Check if there are actual changes
          if ! cmp -s requirements.txt requirements.txt.new; then
            mv requirements.txt.new requirements.txt
            echo "Changes detected in requirements.txt"
            
            # Commit and push changes
            git add requirements.txt
            git commit -m "build(deps): update all dependencies to latest versions"
            git push -f origin deps/update-all

            # Create PR
            echo "Creating PR..."
            gh pr create \
              --title "build(deps): update all dependencies" \
              --body "Update all dependencies to their latest versions" \
              --label "dependencies" \
              --label "python" \
              --base main

            # Wait for checks to complete
            echo "Waiting for checks to complete..."
            sleep 180

            # Enable auto-merge
            pr_number=$(gh pr list --json number,headRefName --jq '.[] | select(.headRefName == "deps/update-all") | .number')
            if [ ! -z "$pr_number" ]; then
              echo "Enabling auto-merge for PR #$pr_number"
              gh pr merge "$pr_number" --auto --merge || true
            fi
          else
            echo "No changes needed in requirements.txt"
            rm requirements.txt.new
          fi
        else
          echo "requirements.txt not found"
          exit 1
        fi
